### ISSUE TITLE
unnecessary data models

### ISSUE THREAD

**Issue by jxtu** [brandeis-llc/r2v-r2vq-python#3]
In `models.py` I defined `Anchor` and `FullEvent` classes for the purpose of easy indexing in database and question generation. For the package release, these two classes seem to be repetitive and unnecessary because essentially they are just simple wrappers of other data classes. Maybe we can remove those here, what do you think? @keighrim

**Comment by keighrim** [comment]
If they are only used in the QG database, I guess they can be refactored into QG code, or QG code may can monkeypatch `models` submodule?

**Comment by jxtu** [comment]
Yes those are for QG only, and QG code won't affect `models`. I may still keep it in the [QG repo](https://github.com/brandeis-llc/r2v-CLEVR-Style-Question-Generation) just for the convenience, but I guess we can take them away in this repo.
