### ISSUE TITLE
creating underspecified data objects

### ISSUE THREAD

**Issue by keighrim** [brandeis-llc/r2v-r2vq-python#4]
For CRL annotation environment, not all fields of a `Token` is necessary. For example, a human CRL annotator does not have to know lemma or pos of tokens to annotate relations and hidden objects. Hence, under currently implementation of the environment, backend database does not store entire `Token` data model. 

However I want to use the same models and write-out code defined in the `models.py` submodule while only providing information available from the annotation environment, when the annotation is exported as CSV. However, currently implementation of `Token` does not allow that, as all fields are *required* by the `attrs` implementation. 

I wonder if there's an easy way to patch the model so that I can create a `Token` object only with, for example, `ID`, `FORM`, `PART`, `RESULT`, `HIDDEN`, `COREF` columns? Or even better, initialize an object without any argument then set those column values afterward?

**Comment by jxtu** [comment]
On branch `issue4` I made some changes to `Token` class:
- Except `id` and `form`, all the other attributes of this class have the default value as `None`
- It's not frozen anymore, which means the value of attributes  can be modified after the class has been initialized

Will this do the work?

**Comment by keighrim** [comment]
This should work! Thanks for working on this. I may edit more classes as needed, now that I know how to make this happen.
